services:

  mysql:
    image: mysql:8.0
    container_name: product-mysql

    restart: unless-stopped

    environment:
      MYSQL_DATABASE: product_db
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3306:3306"

    volumes:
      - product_mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "product_user",
          "-pproduct_password"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  product_mysql_data: